name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-infra-action
        name: build infra structure
        with:
          bicepFilePath: "./iac/main.bicep"
          armFilePath: "./iac/main.json"